#!bin/bash

all:
	g++ craps_game.cpp -o craps_game
	g++ craps_helper.cpp -o craps_helper
	g++ craps_io.cpp -o craps_io

craps:
	g++ craps.cpp -o craps

craps_game:
	g++ craps_game.cpp -o craps_game

craps_helper:
	g++ craps_helper.cpp -o craps_helper

craps_io: 
	g++ craps_io.cpp -o craps_io

clean:
	rm -rf craps_game
	rm -rf craps_helper
	rm -rf craps_io
